POST http://localhost:9328/SV1/StudentNames/Insert/SchemaColumnsOnly
Content-Type: application/json

{
  "StudentName": "",
  "Mobile": "",
  "Email": "",
  "CollegeName": "",
  "Country": "",
  "EntranceRank": "",
  "YearPassOut": "",
  "Back_logs": "",
  "RollNumber": "",
  "file": "",
  "GitLink": "",
  "Intern2025": ""
}
