POST http://localhost:9328/SV1/Task2/Insert/AsIsNoPk
Content-Type: application/json

{
  "StudentName": "",
  "Mobile": "",
  "Email": "",
  "CollegeName": "",
  "YearPassOut": "",
  "RollNumber": "",
  "GitLink": "",
  "HostLink": ""
}
