POST http://localhost:9328/SV1/Task2/GroupBy/Sum
Content-Type: application/json

[
	{
  "StudentName": "",
  "Mobile": "",
  "Email": "",
  "CollegeName": "",
  "YearPassOut": "",
  "RollNumber": "",
  "GitLink": "",
  "HostLink": ""
}
]